# PROJECT OPTIONS
# ===============

[project]

# Name of project
project_name = "untitled"

# Description of <pack.mcmeta>
description = "#Made by using Kiwi Compiler"

# Entry file to start compiling process
entry_file = "main"

# Version to compile for
mc_version = "1.16.5"


# ADDITIONAL OPTIONS
# ==================

[options]

# Directories with libraries
include_directories = ["lib"]

# Entry point function
entry_function = "main"

# Directory to generate output datapack
output_directory = "bin"

# Choose between "public" / "private" to configure default scope of namespace
default_scope = "public"

# It's useless at the moment
space_separator = "."
